[package]
name = "mikktspace"
version = "0.1.0"
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
description = "Mikkelsen tangent space algorithm"
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[dev-dependencies]
cgmath = "0.15"

[[example]]
name = "generate"
