[package]
name = "mikktspace-sys"
version = "0.1.0"
authors = ["alteous <alteous@outlook.com>"]
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[dependencies]
gltf = "0.7"

[[example]]
name = "generate"